/* USER CODE BEGIN Header */
/*
 * ============================================================
 *  Smart Diabetic Foot Shoe — Phase 1 Firmware (STM32 Port)
 *  Target:    STM32F103C8T6 "Blue Pill" — Proteus VSM Simulation
 *  Framework: STM32 HAL, generated via STM32CubeIDE/CubeMX
 * ------------------------------------------------------------
 *  Pin Map:
 *    PA0  - FSR Heel      (ADC1_IN0)
 *    PA1  - FSR Midfoot   (ADC1_IN1)
 *    PA2  - FSR Forefoot  (ADC1_IN2)
 *    PA3  - LM35 Zone 1   (ADC1_IN3)
 *    PA4  - LM35 Zone 2   (ADC1_IN4)
 *    PB0  - DHT11 Data    (bit-banged GPIO)
 *    PA8  - Buzzer        (GPIO output)
 *    PA9/PA10 - USART1 TX/RX -> CSV stream to Virtual Terminal
 * ------------------------------------------------------------
 *  This file assumes a CubeMX-generated project. SystemClock_Config(),
 *  MX_GPIO_Init(), MX_ADC1_Init() and MX_USART1_UART_Init() are normally
 *  auto-generated by CubeMX from your .ioc pin configuration — keep all
 *  of YOUR logic inside "USER CODE" style sections so regenerating the
 *  project from CubeMX never wipes out the sensor/algorithm code below.
 * ============================================================
 */
/* USER CODE END Header */

#include "main.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

ADC_HandleTypeDef  hadc1;
UART_HandleTypeDef huart1;

/* ---------------------- Timing ---------------------- */
#define SAMPLE_INTERVAL_MS   500U
static uint32_t lastSampleTick = 0;

/* ---------------------- Calibration / Thresholds ---------------------- */
#define TEMP_DIFF_ALERT_C    2.2f
#define PRESSURE_ALERT_ADC   3300   /* 12-bit ADC (0-4095), tune while simulating */
#define HUMIDITY_ALERT_PCT   70.0f
#define RISK_ALERT_SCORE     60

/* ---------------------- Data Structures ---------------------- */
typedef struct {
    uint16_t heel;
    uint16_t midfoot;
    uint16_t forefoot;
} PressureData_t;

typedef struct {
    float zone1;
    float zone2;
} TemperatureData_t;

typedef struct {
    PressureData_t    pressure;
    TemperatureData_t temperature;
    float             humidity;
    uint8_t           humidityValid;
    uint8_t           riskScore;
} SensorSnapshot_t;

/* ---------------------- Function Prototypes ---------------------- */
static void     DWT_Init(void);
static void     delay_us(uint32_t us);

static uint16_t readADCChannel(uint32_t channel);
static PressureData_t    readPressureSensors(void);
static TemperatureData_t readTemperatureSensors(void);
static float    adcToCelsius(uint16_t adcValue);

static void     DHT11_SetPinOutput(void);
static void     DHT11_SetPinInput(void);
static uint8_t  readDHT11(float *humidity);

static uint8_t  computeRiskScore(const SensorSnapshot_t *snap);
static void     checkAlerts(const SensorSnapshot_t *snap);
static void     sendSnapshotCSV(const SensorSnapshot_t *snap);

/* These four are generated by CubeMX in a real project - declared here
 * only so this file compiles standalone for reference. */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_USART1_UART_Init(void);

/* ---------------------- Main ---------------------- */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    DWT_Init();

    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_USART1_UART_Init();

    const char header[] =
        "timestamp_ms,heel,midfoot,forefoot,temp1_C,temp2_C,humidity_pct,risk_score\r\n";
    HAL_UART_Transmit(&huart1, (uint8_t *)header, strlen(header), HAL_MAX_DELAY);

    while (1)
    {
        uint32_t now = HAL_GetTick();

        if ((now - lastSampleTick) >= SAMPLE_INTERVAL_MS)
        {
            lastSampleTick = now;

            SensorSnapshot_t snap;
            snap.pressure       = readPressureSensors();
            snap.temperature    = readTemperatureSensors();
            snap.humidityValid  = readDHT11(&snap.humidity);
            snap.riskScore      = computeRiskScore(&snap);

            sendSnapshotCSV(&snap);
            checkAlerts(&snap);
        }
    }
}

/* ---------------------- Microsecond delay (DWT cycle counter) ---------------------- */
static void DWT_Init(void)
{
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

static void delay_us(uint32_t us)
{
    uint32_t start = DWT->CYCCNT;
    uint32_t ticks = us * (SystemCoreClock / 1000000U);
    while ((DWT->CYCCNT - start) < ticks) { }
}

/* ---------------------- ADC Reading ---------------------- */
static uint16_t readADCChannel(uint32_t channel)
{
    ADC_ChannelConfTypeDef sConfig = {0};
    sConfig.Channel      = channel;
    sConfig.Rank         = ADC_REGULAR_RANK_1;
    sConfig.SamplingTime = ADC_SAMPLETIME_55CYCLES_5;
    HAL_ADC_ConfigChannel(&hadc1, &sConfig);

    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
    uint16_t value = HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);

    return value;
}

static PressureData_t readPressureSensors(void)
{
    PressureData_t p;
    p.heel     = readADCChannel(ADC_CHANNEL_0);
    p.midfoot  = readADCChannel(ADC_CHANNEL_1);
    p.forefoot = readADCChannel(ADC_CHANNEL_2);
    return p;
}

static TemperatureData_t readTemperatureSensors(void)
{
    TemperatureData_t t;
    t.zone1 = adcToCelsius(readADCChannel(ADC_CHANNEL_3));
    t.zone2 = adcToCelsius(readADCChannel(ADC_CHANNEL_4));
    return t;
}

static float adcToCelsius(uint16_t adcValue)
{
    /* LM35: 10 mV/°C, 3.3V reference on STM32 (not 5V like the Arduino version),
     * 12-bit ADC (0-4095). */
    float voltage = (adcValue * 3.3f) / 4095.0f;
    return voltage * 100.0f;
}

/* ---------------------- DHT11 (bit-banged, PB0) ---------------------- */
static void DHT11_SetPinOutput(void)
{
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = GPIO_PIN_0;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOB, &gpio);
}

static void DHT11_SetPinInput(void)
{
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin  = GPIO_PIN_0;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(GPIOB, &gpio);
}

static uint8_t readDHT11(float *humidity)
{
    uint8_t data[5] = {0};

    /* --- Start signal --- */
    DHT11_SetPinOutput();
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET);
    HAL_Delay(18);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET);
    delay_us(30);
    DHT11_SetPinInput();

    /* --- Wait for sensor response (with timeouts so we never hang) --- */
    uint32_t timeout = 0;
    while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_SET) {
        if (++timeout > 1000) return 0;
        delay_us(1);
    }
    timeout = 0;
    while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_RESET) {
        if (++timeout > 1000) return 0;
        delay_us(1);
    }
    timeout = 0;
    while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_SET) {
        if (++timeout > 1000) return 0;
        delay_us(1);
    }

    /* --- Read 40 data bits --- */
    for (uint8_t i = 0; i < 40; i++)
    {
        timeout = 0;
        while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_RESET) {
            if (++timeout > 1000) return 0;
            delay_us(1);
        }

        delay_us(40); /* sample mid-bit: high >28us => '1', shorter => '0' */
        uint8_t bit = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_SET) ? 1 : 0;

        timeout = 0;
        while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_0) == GPIO_PIN_SET) {
            if (++timeout > 1000) break;
            delay_us(1);
        }

        data[i / 8] <<= 1;
        data[i / 8] |= bit;
    }

    uint8_t checksum = data[0] + data[1] + data[2] + data[3];
    if (checksum != data[4]) return 0;

    *humidity = (float)data[0];
    return 1;
}

/* ---------------------- Risk Fusion (same weighted model as the Arduino version) ---------------------- */
static uint8_t computeRiskScore(const SensorSnapshot_t *snap)
{
    uint16_t score = 0;

    uint16_t maxPressure = snap->pressure.heel;
    if (snap->pressure.midfoot  > maxPressure) maxPressure = snap->pressure.midfoot;
    if (snap->pressure.forefoot > maxPressure) maxPressure = snap->pressure.forefoot;
    if (maxPressure > PRESSURE_ALERT_ADC) score += 40;

    float tempDiff = fabsf(snap->temperature.zone1 - snap->temperature.zone2);
    if (tempDiff > TEMP_DIFF_ALERT_C) score += 40;

    if (snap->humidityValid && snap->humidity > HUMIDITY_ALERT_PCT) score += 20;

    if (score > 100) score = 100;
    return (uint8_t)score;
}

/* ---------------------- Alerting ---------------------- */
static void checkAlerts(const SensorSnapshot_t *snap)
{
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8,
                       (snap->riskScore >= RISK_ALERT_SCORE) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/* ---------------------- CSV Output over USART1 ---------------------- */
static void sendSnapshotCSV(const SensorSnapshot_t *snap)
{
    char line[128];
    int len = snprintf(line, sizeof(line),
                        "%lu,%u,%u,%u,%.2f,%.2f,%.1f,%u\r\n",
                        (unsigned long)HAL_GetTick(),
                        snap->pressure.heel, snap->pressure.midfoot, snap->pressure.forefoot,
                        snap->temperature.zone1, snap->temperature.zone2,
                        snap->humidityValid ? snap->humidity : -1.0f,
                        snap->riskScore);

    HAL_UART_Transmit(&huart1, (uint8_t *)line, len, HAL_MAX_DELAY);
}

/* ============================================================
 *  Peripheral init stubs below are normally CubeMX-generated.
 *  Configure in the .ioc file: ADC1 channels 0-4 (PA0-PA4),
 *  USART1 at 9600-8-N-1 (PA9/PA10), GPIO PA8 as output (buzzer),
 *  PB0 left as a plain GPIO (driven manually by the DHT11 code).
 * ============================================================ */
